# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-27 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='ois_pay',
            new_name='is_pay',
        ),
    ]
