# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-22 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='goodsinfo',
            options={'ordering': ['pk']},
        ),
    ]
