# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-23 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0003_goodsinfo_gdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cclass',
            field=models.CharField(default='', max_length=20),
        ),
    ]
