# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-21 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0004_auto_20180520_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sperson', models.CharField(max_length=20)),
                ('saddress', models.CharField(max_length=100)),
                ('syoubian', models.CharField(default='', max_length=6, null=True)),
                ('sphone', models.CharField(max_length=11)),
            ],
            options={
                'ordering': ['pk', 'sperson'],
            },
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='ushou',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='uyoubian',
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_user.UserInfo'),
        ),
    ]
