# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-21 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0006_auto_20180521_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
    ]
