# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-27 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_cart', '0002_cartinfo_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartinfo',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
